apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/instance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    allocatedStorage: 10
    dbName: mydb
    engine: mysql
    engineVersion: "5.7"
    instanceClass: db.t3.micro
    parameterGroupName: default.mysql5.7
    passwordSecretRef:
      name: {{ .Values.secretName }}
      key: password
      namespace: {{ .Values.namespace }} 
    region: us-east-1
    skipFinalSnapshot: true
    username: foo
