---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: dev-igw
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    tags:
      Name: dev-igw
    vpcIdRef:
      name: dev-main
