---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: {{ .Values.environment }}-igw
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    tags:
      Name: {{ .Values.environment }}-igw
    vpcIdRef:
      name: {{ .Values.environment }}-main
