---
apiVersion: rds.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/subnetgroup
  labels:
    testing.upbound.io/example-name: default
  name: example-subnetgroup
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    subnetIdRefs:
      - name: {{ .Values.environment }}-private-{{ .Values.aws_region }}a
      - name: {{ .Values.environment }}-private-{{ .Values.aws_region }}b
    tags:
      Name: My DB subnet group
---
  apiVersion: network.aws.crossplane.io/v1alpha3
  kind: SecurityGroup
  metadata:
    name: sample-rds-sg
  spec:
    vpcIdRef:
      name: {{ .Values.environment }}-main
    groupName: my-cool-rds-sg
    description: open rds access to crossplane workload
    reclaimPolicy: Delete
    ingress:
      - fromPort: 5432
        toPort: 5432
        protocol: tcp
        cidrBlocks:
          - cidrIp: 0.0.0.0/0
            description: all ips
    providerRef:
      name: aws-provider