---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: {{ .Values.environment }}-main
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    tags:
      Name: {{ .Values.environment }}-main
