apiVersion: apigatewayv2.aws.upbound.io/v1beta1
kind: API
metadata:
  labels:
    upjet.upbound.io/test-group: apigatewayv2-http
  name: auth-api
spec:
  forProvider:
    name: {{ .Values.environment }}-test-http-api
    protocolType: HTTP
    region: {{ .Values.aws_region }} 
