apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/instance
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: example-dbinstance
  name: example-dbinstance
spec:
  forProvider:
    allocatedStorage: 20
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    backupWindow: 09:46-10:16
    engine: mysql
    engineVersion: "5.7"
    instanceClass: db.t3.large
    applyImmediately: true
    publiclyAccessible: true
    dbSubnetGroupNameRef:
      name: {{ .Values.environment }}-example-subnetgroup
    vpcSecurityGroupIdRefs:
      - name: {{ .Values.environment }}-sample-rds-sg
    maintenanceWindow: Mon:00:00-Mon:03:00
    name: example
    passwordSecretRef:
      key: password
      name: rds-master-password
      namespace: {{ .Values.namespace }}
    publiclyAccessible: false
    region: {{ .Values.aws_region }} 
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp2
    username: adminuser
  writeConnectionSecretToRef:
    name: example-dbinstance-out
    namespace: {{ .Values.namespace }}