---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: {{ .Values.environment }}-private
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    tags:
      Name: {{ .Values.environment }}-private
    vpcIdRef:
      name: {{ .Values.environment }}-main
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: {{ .Values.environment }}-private
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: {{ .Values.environment }}-nat
    region: {{ .Values.aws_region }} 
    routeTableIdRef:
      name: {{ .Values.environment }}-private
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: {{ .Values.environment }}-public
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    tags:
      Name: {{ .Values.environment }}-public
    vpcIdRef:
      name: {{ .Values.environment }}-main
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: {{ .Values.environment }}-public
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: {{ .Values.environment }}-igw
    region: {{ .Values.aws_region }} 
    routeTableIdRef:
      name: {{ .Values.environment }}-public
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: {{ .Values.environment }}-private-{{ .Values.aws_region }}a
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    routeTableIdRef:
      name: {{ .Values.environment }}-private
    subnetIdRef:
      name: {{ .Values.environment }}-private-{{ .Values.aws_region }}a
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: {{ .Values.environment }}-private-{{ .Values.aws_region }}b
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    routeTableIdRef:
      name: {{ .Values.environment }}-private
    subnetIdRef:
      name: {{ .Values.environment }}-private-{{ .Values.aws_region }}b
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: {{ .Values.environment }}-public-{{ .Values.aws_region }}a
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    routeTableIdRef:
      name: {{ .Values.environment }}-public
    subnetIdRef:
      name: {{ .Values.environment }}-public-{{ .Values.aws_region }}a
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: {{ .Values.environment }}-public-{{ .Values.aws_region }}b
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    routeTableIdRef:
      name: {{ .Values.environment }}-public
    subnetIdRef:
      name: {{ .Values.environment }}-public-{{ .Values.aws_region }}b
