apiVersion: rds.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/subnetgroup
  labels:
    testing.upbound.io/example-name: default
  name: {{ .Values.environment }}-example-subnetgroup
spec:
  forProvider:
    region: {{ .Values.aws_region }} 
    subnetIdRefs:
      - name: {{ .Values.environment }}-public-{{ .Values.aws_region }}a
      - name: {{ .Values.environment }}-public-{{ .Values.aws_region }}b
    tags:
      Name: My Public DB subnet group